### ISSUE TITLE
Debian Release Mapping needs update

### ISSUE THREAD

**Issue by deshui123** [jgsqware/clairctl#109]
When run clair using docker-compose and check clair logs. There is error about Debian:

{"Event":"Debian buster is not mapped to any version number (eg. Jessie-\u003e8). Please update me.","Level":"warning","Location":"debian.go:128","Time":"2018-01-30 03:03:12.826406"}

Find some related issue in https://github.com/coreos/clair/pull/416/files

**Comment by jgsqware** [comment]
This is not related to clairctl, need to update clair docker image.
