### ISSUE TITLE
error building docker app in jenkins

### ISSUE THREAD

**Issue by bronsonatcs** [jgsqware/clairctl#131]
When i run my build i get this error :  Caused: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Permission denied: /var/run/docker.sock

not sure what is causing this, trying to build a docker app in jenkins.

**Comment by jgsqware** [comment]
This is not linked to clairctl, it appears your Jenkins agent doesn't right to use the docker socket
