### ISSUE TITLE
Cannot build recent commits:  (cannot find package "github.com/jgsqware/xnet")

### ISSUE THREAD

**Issue by onzo-engineering** [jgsqware/clairctl#14]
Hi, 
I am keen to build and test , however I am hitting the same build failures as travis-ci is 
which is the following error: 

cannot find package "github.com/jgsqware/xnet"

Any suggestions on what I can do to fix this?

thanks in advance.

**Comment by jgsqware** [comment]
Will fix that soon

**Comment by jgsqware** [comment]
fixed by https://github.com/jgsqware/clairctl/commit/6c8caab612aa156c4b5ef37fc3788c7797cb104a

**Comment by onzo-engineering** [comment]
Awesome, just tested building it from scratch and works fine. 
Thanks man.

**Comment by jgsqware** [comment]
With pleasure!
