### ISSUE TITLE
Running Clairctl inside alpine - always tries to talk to localhost, doesnt read the config file

### ISSUE THREAD

**Issue by obikay200** [jgsqware/clairctl#20]
Hi jgsqware

Ive tried to place the binary inside a container by mounting a volume, which executes ok, but when i try to do a health check it fails.

when i run a debug it shows the address as http://localhost:6061/ even though i have specified it in the clairctl.yml file.

./clairctl  health --config /root/clairctl.yml --log-level debug
2017-03-08 10:17:12.813956 D | config: Using config file: /root/clairctl.yml
2017-03-08 10:17:12.814105 D | clair: requesting health on: http://localhost:6061/health
2017-03-08 10:17:12.928237 E | clair: requesting Clair health: Get http://localhost:6061/health: dial tcp [::1]:6061: getsockopt: connection refused

Clair: ✘

**Comment by jgsqware** [comment]
Good catch ! I will fix this!

**Comment by obikay200** [comment]
i debugged it on the localhost and it does the same
uses the defualt.

Thanks

**Comment by jgsqware** [comment]
What is the content of your `clairctl.yml`?

**Comment by obikay200** [comment]
clair:
  port: 6060
  healthPort: 6061
  uri: http://172.18.0.2
  report:
    path: ./reports
    format: html
docker:
  insecure-registries: 
    - "my-own-registry:5000"

**Comment by obikay200** [comment]
which is what cought my eye on debug that is still reaching to http://localhost

**Comment by jgsqware** [comment]
The version 1.2.7 should fix it. Moreover, a docker image is now provided
