### ISSUE TITLE
Question: How does clairctl solve image pull vs push issue?

### ISSUE THREAD

**Issue by sunny137** [jgsqware/clairctl#26]
Came here from 

https://github.com/coreos/clair/issues/112

One of the comment there indicates that hyperclair addresses the issue of starting http server to let clair pull image. Does hyperclair push the image/layers to clair? As per my understanding clair doesnt support POSTing of layers/images, any inputs would be useful.

**Comment by jzelinskie** [comment]
The API always you to specify a URL or a local filesystem path to the layer.
For security, the Quay integration with Clair provides Clair with signed URLs that expire quickly, rather than giving Clair full access to the registry un-authenticated.

**Comment by sunny137** [comment]
Got it. Thanks.
