### ISSUE TITLE
Login and Logout subcommands shown in README.md not available in latest revision

### ISSUE THREAD

**Issue by chr2002ca** [jgsqware/clairctl#28]
I just downloaded and installed the most recent revision of clairctl yesterday(4/11/17).  In the README.md here, it shows login/logout commands are available:

  login       Log in to a Docker registry
  logout      Log out from a Docker registry

However, in the usage for clairctl, those are not available:

$ ./clairctl --help
Analyze your docker image with Clair, directly from your registry or local images.

Usage:
  clairctl [command]

Available Commands:
  analyze     Analyze Docker image
  delete      Delete Docker image
  health      Get Health of clairctl and underlying services
  pull        Pull Docker image to Clair
  push        Push Docker image to Clair
  report      Generate Docker Image vulnerabilities report
  version     Get Versions of Clairctl and underlying services

Our private Docker registry requires authentication, so these commands or a similar functionality are vital.  Without it, were seeing:

$ ./clairctl --config /apps/clair/conf/clairctl.yml report nexus-docker.fico.com:444/test-image
client quit unexpectedly
2017-04-12 16:54:59.894780 C | cmd: retrieving manifest for "nexus-docker.fico.com:444/test-image": Head https://nexus-docker.fico.com:444/v2/test-image/manifests/latest: no basic auth credentials

Are login/logout commands or similar authentication functionality available in the most recent revision?  

Thanks.

**Comment by jgsqware** [comment]
Hello, the login/logout is not available anymore. It use the login method
of Docker. So if you are logged with docker, you are logged with Clairctl
