### ISSUE TITLE
clairctl fails when run from within a container

### ISSUE THREAD

**Issue by leopoldodonnell** [jgsqware/clairctl#30]
For use within a CICD pipeline tool like Jenkins, it would useful/necessary to work within a container.

Currently clairctl has difficulty binding to an address that would be useful to Clair from within a container. It is possible to set clairctl.ip to something clair can connect to (the container host), but when this is done, clairctl can't bind.

One solution may be to use the local ip setting solely for transmission to clair and use the default or the one specified by 'interface' for the actual bind

If I've just misunderstood how to set it up with a container, please let me know

**Comment by jgsqware** [comment]
It's already possible via the clairctl.yml file.
