### ISSUE TITLE
Error when trying to generate HTML report

### ISSUE THREAD

**Issue by hExPY** [jgsqware/clairctl#36]
Hey guys, 

i get this error when i try to generate html reports.

```
2017-05-03 03:32:36.205683 C | cmd: generating HTML report: rendering HTML report: template: analysis-template:512:45: executing "analysis-template" at <.LastLayer.Name>: can't evaluate field LastLayer in type clair.ImageAnalysis
```

Do you guys know how to fix?

Kind regards,

**Comment by jdel** [comment]
I have the same issue with a fresh build from master.

**Comment by jdel** [comment]
Seems to be related to https://github.com/jgsqware/clairctl/pull/33#issuecomment-298491484

**Comment by jdel** [comment]
Tried the proposed solution, 

clairctl will generate reports after running 

```
go get -u github.com/jteeuwen/go-bindata/...
cd $GOPATH/src/github.com/jgsqware/clairctl
go generate ./clair
```

**Comment by jgsqware** [comment]
True, i need to automate the build for this.

Le jeu. 4 mai 2017 17:58, Julien Del-Piccolo <notifications@github.com> a
écrit :

**Comment by mnick-nm** [comment]
I am running into this issue and new to go so I'm not sure if I'm following those steps correctly - or if I even have go configured correctly to work.  But those steps aren't changing my output.
` cmd: generating HTML report: rendering HTML report: template: analysis-template:512:45: executing "analysis-template" at <.LastLayer.Name>: can't evaluate field LastLayer in type clair.ImageAnalysis
`

**Comment by jgsqware** [comment]
Do you have this on the master branch?

**Comment by mnick-nm** [comment]
I do.  The strange thing is that the error is saying `LastLayer` while the analysis-template.html file I'm using has the new `MostRecentLayer` name.

**Comment by chrismoos** [comment]
@mnick-nm After running the command `go generate ./clair` make sure to re-compile `clairctl`:

```
$ cd $GOPATH/src/github.com/jgsqware/clairctl && go build .
```

This is because the template is included with `go-bindata` in the binary -- it's not loaded at runtime from the HTML file.

**Comment by jgsqware** [comment]
is working now?

**Comment by jgsqware** [comment]
should be fixed in master.
