### ISSUE TITLE
Clairctl version doesn't report the right value

### ISSUE THREAD

**Issue by jdel** [jgsqware/clairctl#4]
Running `clairctl version` doesn't output version of clairctl or clair.

```
sf-clair ~ # clairctl version

Clairctl version
```

**Comment by jdel** [comment]
Issue still persist with build 5d7ae72

**Comment by jgsqware** [comment]
Thanks for reporting, the version is integrated during the build. 
if you want to build/run locally the go project itself you should is this flag to load the version:

```
go run -ldflags "-X github.com/jgsqware/clairctl/cmd.version=$(cat VERSION)" main.go version
```

```
go build -ldflags "-X github.com/jgsqware/clairctl/cmd.version=$(cat VERSION)" -v
```
