### ISSUE TITLE
How to setup clairctl on CentOS7?

### ISSUE THREAD

**Issue by liuyihe111** [jgsqware/clairctl#44]
I very much like the work you guys are doing on this.
Could you please provide some guidance for the setup of clairctl on CentOS7?
Thank you very much !

**Comment by lcgkm** [comment]
It's just a CLI tool, no OS requirement.
You can build it by yourself. 
Please read https://github.com/jgsqware/clairctl/blob/master/README.md

**Comment by jgsqware** [comment]
You can find the release binary here: https://github.com/jgsqware/clairctl/releases

**Comment by liuyihe111** [comment]
@lcgkm Thank you，I installed Clair on my OS, so I want to setup a tool to use it. I have read  https://github.com/jgsqware/clairctl/blob/master/README.md, but I didn't understand the steps
to setup and use it. Could you please detail the guidance ? Thank you very much!

**Comment by liuyihe111** [comment]
@jgsqware Thank you very much! But I want to know how to use  it with Clair? Could you please tell me steps? Thank you

**Comment by lcgkm** [comment]
Step1. Setup a Clair Instance......
https://github.com/coreos/clair
Step2. modify clairctl.yml confgiuration file, to make sure Clairctl can connect to Clair
Step3. Just use to Clairctl PUSH/ANALAZE/REPORT operation

**Comment by liuyihe111** [comment]
@lcgkm Thanks for your quick response. I have done the step1, but I don't know how to do step2.

**Comment by lcgkm** [comment]
example:
https://github.com/jgsqware/clairctl/blob/master/clairctl.yml.default

Try it by yourself.

**Comment by jgsqware** [comment]
Clairctl interact with the Clair API. Clairctl should be configured by a
`.clairctl.yml` inside your $HOME folder, or in the directory where you run
Clair. As @lcgkm says, you have to specify some information there, where
Clair is located, on which port, etc...

**Comment by liuyihe111** [comment]
@jgsqware Do you means that I only need to build a "clairctl.yml"file? I have tried and modified the file. But when I do the command "clairctl analyze……", the result shows that "bash: clairctl: can't find this command".What should I do ?
Thank you very much!

**Comment by jgsqware** [comment]
You have to install the binary. Check the new README you will find how to install it
