### ISSUE TITLE
CI/CD integration

### ISSUE THREAD

**Issue by dgonzalez** [jgsqware/clairctl#55]
Hi, it would be amazing if clairctl had a command that could exit with non-zero code if certain vulnerabilities (or certain level) were present on an image so that it could be integrated with a CI/CD pipeline

**Comment by jgsqware** [comment]
Good remark, I needed to today. I will implement it on analyze cmd

**Comment by dgonzalez** [comment]
I would suggest you to implement it in another command so you can run analyze on background and having something like:
```
clairctl filter --min-severity=Medium
```
This one does not need to be CPU intensive like analyze so you would save a lot of resources when deploying clair. Thanks

**Comment by jgsqware** [comment]
Analyze doesn't take resources. It gather info in clair. So we cannot
filter if it has not been analyze first.

**Comment by dgonzalez** [comment]
Oh I see the picture now... thanks!
