### ISSUE TITLE
Clairctl push cannot find its own ip address on a mac

### ISSUE THREAD

**Issue by jdel** [jgsqware/clairctl#9]
Clairctl push cannot find its own ip address on a mac

```
jdel@macbook $ clairctl --log-level debug push jgsqware/registry-ui -l
DEBU[0000] No config file used
INFO[0000] retrieving docker0 interface as local IP
client quit unexpectedly
FATA[0000] retrieving internal server IP: retrieving docker0 interface ip: exec: "ip": executable file not found in $PATH
```

I do not see any `docker0` interface on my mac at all. However, from my containers I can ping my mac using its primary IP address. So I guess it would be safe to use `ipconfig getifaddr en0` to get a mac's IP address if `uname` returns "Darwin".

**Comment by jgsqware** [comment]
Fixed, you can configure a specific interface in yml, or it will look for `docker0` if not found, use the first broadcast ipv4 interface
