### ISSUE TITLE
Help in setting up clairctl

### ISSUE THREAD

**Issue by qf31** [jgsqware/clairctl#94]
Hi,

i have faced difficulties in setting up with clairctl. i have followed the commands as stated:

$ git clone git@github.com:jgsqware/clairctl.git $GOPATH/src/github.com/jgsqware/clairctl
$ cd $GOPATH/src/github.com/jgsqware/clairctl
$ docker-compose up -d postgres

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1. For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Here is the docker-compose.yml :   

version: '2.1'

services:
  postgres:
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - ./docker-compose-data/postgres-data/:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_USER=clair
      - POSTGRES_DB=clair
    
  clair:
    image: quay.io/coreos/clair:v2.0.0
    restart: unless-stopped
    volumes:
      - ./docker-compose-data/clair-config/:/config/:ro
      - ./docker-compose-data/clair-tmp/:/tmp/:rw
    depends_on: 
      postgres:
        condition: service_started
    command: [--log-level=debug, --config, /config/config.yml]
    
  clairctl:
    image: jgsqware/clairctl:latest
    restart: unless-stopped
    environment: 
      - DOCKER_API_VERSION=1.24
    volumes:
      - ./docker-compose-data/clairctl-reports/:/reports/:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on: 
      clair: 
        condition: service_started

changing the version number to '2.0' or '2' result in :

services.clairctl.depends_on contains an invalid type, it should be an array
services.clair.depends_on contains an invalid type, it should be an array

## **Can anyone advise me what is wrong and what should i do?  Thanks**

Additional information:

$ docker version

Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

$ go version
go version go1.8 linux/amd64

**Comment by jdel** [comment]
Hello, which version of docker-compose are you using ?

**Comment by qf31** [comment]
hi 
this is the  docker-compose version i am using :

$ docker-compose -v
docker-compose version 1.8.0, build unknown

**Comment by jdel** [comment]
docker-compose 1.8.x is over a year old. Please update docker-compose.
